#adapted from example in docker documentation
version: '3'

services:
  web:
    build: .
    volumes:
       - .:/code
    #ports:
       #- 8000:8000
    command: python /code/finalproject/mysite/manage.py runserver 0.0.0.0:8000
    restart: always
    expose:
      - 8000
    user: 1001:1002
    links:
      - redis:redis

  nginx:
    restart: always
    build: ./nginx/
    depends_on:
      - web
    ports:
      - 80:80
    links:
    - web:web

  redis:
    image: redis:latest
    expose:
      - 6379
